#!/bin/bash


DALCLICK_SCRIPTS_DIR="$(dirname "$0")"
cd "$DALCLICK_SCRIPTS_DIR"
PWDIR="$(pwd -P)"
DALCLICK_SCRIPTS_DIRNAME="${PWDIR##*/}"
MODE="$1"
UTILS=""

. get_config

[[ -f "$FILE_BROWSER" ]] || FILE_BROWSER=""
[[ -f "$PDF_VIEWER" ]] || PDF_VIEWER=""

SCANTAILOR_PATH="/opt/src/scantailor-enhanced/scantailor"
[[ -f "$SCANTAILOR_PATH" ]] || SCANTAILOR_PATH=""

PDFBEADS_PATH="/opt/src/pdfbeads-kopi/bin/pdfbeads"
[[ -f "$PDFBEADS_PATH" ]] || PDFBEADS_PATH=""

# cd /opt/src/chdkptp

export LUA_PATH="./lua/?.lua;../$DALCLICK_SCRIPTS_DIRNAME/?.lua;/opt/src/chdkptp-lib/lua/?.lua"
echo "LUA_CPATH:$LUA_CPATH"
export LUA_CPATH="/usr/lib/lua/5.2/?.so;/usr/local/lib/lua/5.2/?.so;/opt/src/chdkptp-lib/lua/?.so"

gsettings set org.gnome.desktop.media-handling automount "false"
gsettings set org.gnome.desktop.media-handling automount-open "false"

echo
echo "Main paths:"
echo
echo " Dalclick working folder: '$DALCLICK_HOME'"
echo " Projects folder: '$DALCLICK_PROJECTS'"
echo " Default rotate - odd: $ROTATE_ODD_DEFAULT"
echo " Default rotate - even: $ROTATE_EVEN_DEFAULT"
echo " Default rotate - single: $ROTATE_SINGLE_DEFAULT"
echo

[[ -d $DALCLICK_PROJECTS ]] || { echo "ERROR: la carpeta de proyectos '$DALCLICK_PROJECTS' no existe, revise la configuracion de directorios."; exit 0; }
[[ -w $DALCLICK_PROJECTS ]] || { echo "ERROR: no tiene los permisos necesarios en '$DALCLICK_PROJECTS'."; exit 0; }

LUA_ERRORS=""

if [[ ! -e "$DALCLICK_HOME" ]]
then
    mkdir $DALCLICK_HOME
fi

if [[ "$MODE" != "" ]]
then
    DALCLICK_MODE="$MODE"
else
    DALCLICK_MODE=""
fi

while
true # Loop forever
do
    lua -e "\
require('lfs')
require('io')
require('os')
--
require('chdkptp')
--
require('lbuf')
require('rawimg')
--
util=require('util')
util:import()
ustime=require('ustime')
fsutil=require('fsutil')
prefs=require('prefs')
varsubst=require('varsubst')
chdku=require('chdku')
cli=require('cli')
exp=require('exposure')
dng=require('dng')
dngcli=require('dngcli')
--
-- chdk = {}
-- chdku = {}
-- function chdk.list_usb_devices() return {} end
-- chdku.rlibs = {}
-- function chdku.rlibs:register() return false end
printf = function(s,...) return io.write(s:format(...)) end
-- lfs = require('lfs')
util2 = require('libs.util2')
dc = require('dalclick')
return dc:main('$DALCLICK_HOME','$DALCLICK_PROJECTS','$PWDIR','$ROTATE_ODD_DEFAULT','$ROTATE_EVEN_DEFAULT','$ROTATE_SINGLE_DEFAULT','$DALCLICK_MODE', '$FILE_BROWSER', '$PDF_VIEWER', '$SCANTAILOR_PATH', '$PDFBEADS_PATH', '$PDFBEADS_QUALITY', '$NOC_MODE', '$DELAY_MODE')" 2> $DALCLICK_HOME/lua_errors
    cat "$DALCLICK_HOME/lua_errors"
    LUA_ERRORS=$( cat "$DALCLICK_HOME/lua_errors" | grep "ERROR" )
    if [[ $LUA_ERRORS != "" ]]
    then
        echo
        echo " Presione <enter> para salir."
        echo -n " >>"
        read tecla
        break
    fi
    if [[ ! -e "$DALCLICK_HOME/loop" ]]
    then
        break
    fi
done

gsettings set org.gnome.desktop.media-handling automount "true"
gsettings set org.gnome.desktop.media-handling automount-open "true"
