#!/bin/bash


DALCLICK_SCRIPTS_DIR="$(dirname "$0")"
cd "$DALCLICK_SCRIPTS_DIR"
PWDIR="$(pwd -P)"
DALCLICK_SCRIPTS_DIRNAME="${PWDIR##*/}"
MODE="$1"


if [[ -f "CONFIG" ]]
 then
  . CONFIG
else
  echo
  echo " Necesita crear el archivo 'CONFIG' en '$DALCLICK_SCRIPTS_DIR/'"
  echo " con la configuración de directorios de su proyecto."
  echo " Renombre el archivo 'CONFIG.example' y reemplace las rutas"
  echo " que considere necesarias."
  echo
  echo " Presione <enter> para salir."
  echo -n " >>"
  read tecla
  exit 0
fi

cd /opt/src/chdkptp

export LUA_PATH="./lua/?.lua;../$DALCLICK_SCRIPTS_DIRNAME/?.lua"

gsettings set org.gnome.desktop.media-handling automount "false"
gsettings set org.gnome.desktop.media-handling automount-open "false"

echo
echo "Main paths:"
echo
echo " Dalclick working folder: '$DALCLICK_HOME'"
echo " Projects folder: '$DALCLICK_PROJECTS'"
echo " Default rotate - odd: $ROTATE_ODD_DEFAULT"
echo " Default rotate - even: $ROTATE_EVEN_DEFAULT"
echo

[[ -d $DALCLICK_PROJECTS ]] || { echo "ERROR: la carpeta de proyectos '$DALCLICK_PROJECTS' no existe, revise la configuracion de directorios."; exit 0; }
[[ -w $DALCLICK_PROJECTS ]] || { echo "ERROR: no tiene los permisos necesarios en '$DALCLICK_PROJECTS'."; exit 0; }

LUA_ERRORS=""

if [[ ! -e "$DALCLICK_HOME" ]]
then
    mkdir $DALCLICK_HOME
fi

if [[ "$MODE" != "" ]]
then
    DALCLICK_MODE="$MODE"
else
    DALCLICK_MODE=""
fi

while
true # Loop forever
do
    ./chdkptp -e"exec dc=require('dalclick')" -e"exec return dc:main('$DALCLICK_HOME','$DALCLICK_PROJECTS','$PWDIR','$ROTATE_ODD_DEFAULT','$ROTATE_EVEN_DEFAULT','$DALCLICK_MODE', '$POST_PROC_SCRIPT')" 2> $DALCLICK_HOME/lua_errors
    cat "$DALCLICK_HOME/lua_errors"
    LUA_ERRORS=$( cat "$DALCLICK_HOME/lua_errors" | grep "ERROR" )
    if [[ $LUA_ERRORS != "" ]]
    then
        echo
        echo " Presione <enter> para salir."
        echo -n " >>"
        read tecla
        break
    fi
    if [[ ! -e "$DALCLICK_HOME/loop" ]]
    then
        break
    fi
done

gsettings set org.gnome.desktop.media-handling automount "true"
gsettings set org.gnome.desktop.media-handling automount-open "true"
