#!/bin/bash

DALCLICK_SCRIPTS_DIR="$(dirname "$0")"
cd "$DALCLICK_SCRIPTS_DIR"
PWDIR="$(pwd -P)"
DALCLICK_SCRIPTS_DIRNAME="${PWDIR##*/}"
DALCLICK_MODE="$1"
if [[ "$DALCLICK_MODE" != "STANDALONE" ]]
then
    DALCLICK_MODE=""
fi

UTILS=""

# este valor por default lo mantenemos por compatibilidad 
# con entornos anteriores
CHDKPTP_PATH="/opt/src/chdkptp"

. get_config

[[ -f "$FILE_BROWSER" ]] || FILE_BROWSER=""
[[ -f "$PDF_VIEWER" ]] || PDF_VIEWER=""

# Default components paths
SCANTAILOR_PATH="/opt/src/scantailor-enhanced/scantailor"
PDFBEADS_PATH="/opt/src/pdfbeads-kopi/bin/pdfbeads"

if [[ -f COMPONENTS ]]; then
. COMPONENTS
fi

[[ -f "$SCANTAILOR_PATH" ]] || {
  echo "Scantailor no instalado, continuar? Y/n"
  read tecla
  if [[ "$tecla" =~ "n"|"N" ]]; then exit 0; fi
  SCANTAILOR_PATH=""
}
[[ -f "$PDFBEADS_PATH" ]] || {
  echo "Pdfbeads no instalado, continuar? Y/n"
  read tecla
  if [[ "$tecla" =~ "n"|"N" ]]; then exit 0; fi
  PDFBEADS_PATH=""
}

if [[ -f TECGRAF_PATH ]]; then
. TECGRAF_PATH
fi

if [[ "$DALCLICK_MODE" == "STANDALONE" ]]; then
   LUA_EXEC=lua5.1
   NO_BLOCK_CONFLICTING_SERVICES=Yes
   #export LUA_PATH="./libs/xmlutils/?.lua;;"
   #export LUA_PATH="./?.lua;;"
else
   export LUA_PATH="./lua/?.lua;$PWDIR/?.lua;;"
fi

# check conflicting services
if [[ "$NO_BLOCK_CONFLICTING_SERVICES" != "Yes" ]]; then
  echo block_conflicting_services
  ./block_conflicting_services 'block' && BLOCK="OK" || BLOCK="Error"
fi

[[ "$BLOCK" == "Error" ]] && {
  echo "gPhoto2:"
  ps aux | pgrep -l gphoto2
  echo "Media Transfer Protocol:"
  ps aux | pgrep -l mtp
  echo ""
  echo "Hubo problemas al intentar suspender 'Gphoto2' y 'Media Transfer Protocol'"
  echo "Estos servicios interfieren con Dalclick y pueden provocar que el"
  echo "enlace USB con las cámaras no funcione o no funcione correctamente,"
  echo "continuar de todas formas? Y/n"
  read tecla
  if [[ "$tecla" =~ "n"|"N" ]]; then exit 0; fi
}

echo
echo "Main paths:"
echo
echo " Dalclick Mode: '$DALCLICK_MODE'"
echo " Dalclick working folder: '$DALCLICK_HOME'"
echo " Projects folder: '$DALCLICK_PROJECTS'"
echo " Default rotate - odd: $ROTATE_ODD_DEFAULT"
echo " Default rotate - even: $ROTATE_EVEN_DEFAULT"
echo " Default rotate - single: $ROTATE_SINGLE_DEFAULT"
echo

[[ -d $DALCLICK_PROJECTS ]] || { echo "ERROR: la carpeta de proyectos '$DALCLICK_PROJECTS' no existe, revise la configuracion de directorios."; exit 0; }
[[ -w $DALCLICK_PROJECTS ]] || { echo "ERROR: no tiene los permisos necesarios en '$DALCLICK_PROJECTS'."; exit 0; }

LUA_ERRORS=""

if [[ ! -e "$DALCLICK_HOME" ]]
then
    mkdir $DALCLICK_HOME
fi

while
true # Loop forever
do
    if [[ "$DALCLICK_MODE" == "STANDALONE" ]]; then
      $LUA_EXEC -e"
chdk = {}
chdku = {}
function chdk.list_usb_devices() return {} end
chdku.rlibs = {}
function chdku.rlibs:register() return false end
printf = function(s,...) return io.write(s:format(...)) end
lfs = require('lfs')
print('lfs: ')
print(lfs)
util = require('libs.util')
print('util: ')
print(util)
dc = require('dalclick')
print('dc: ')
print(dc)
sys = require('libs.standalone_sys')
print('sys: ')
print(sys)
-- sys.sleep(1000)
return dc:main(
'$DALCLICK_HOME','$DALCLICK_PROJECTS','$PWDIR','$ROTATE_ODD_DEFAULT',
'$ROTATE_EVEN_DEFAULT','$ROTATE_SINGLE_DEFAULT','$DALCLICK_MODE', 
'$FILE_BROWSER', '$PDF_VIEWER', '$SCANTAILOR_PATH', '$SCANTAILOR_ADV_PATH', 
'$PDFBEADS_PATH', '$PDFBEADS_QUALITY', '$NOC_MODE', '$DELAY_MODE', 'GPHOTO2')
" 2> "$DALCLICK_HOME/lua_errors"
    else
      cd "$CHDKPTP_PATH" || { echo "ERROR: No existe '$CHDKPTP_PATH'"; exit 1; }
      ./chdkptp -e"exec dc=require('dalclick')" -e"exec return dc:main(
'$DALCLICK_HOME','$DALCLICK_PROJECTS','$PWDIR','$ROTATE_ODD_DEFAULT',
'$ROTATE_EVEN_DEFAULT','$ROTATE_SINGLE_DEFAULT','$DALCLICK_MODE', 
'$FILE_BROWSER', '$PDF_VIEWER', '$SCANTAILOR_PATH', '$SCANTAILOR_ADV_PATH', 
'$PDFBEADS_PATH', '$PDFBEADS_QUALITY', '$NOC_MODE', '$DELAY_MODE', 'CHDKPTP')
" 2> "$DALCLICK_HOME/lua_errors"
    fi
    cat "$DALCLICK_HOME/lua_errors"
    LUA_ERRORS=$( cat "$DALCLICK_HOME/lua_errors" | grep "ERROR" )
    if [[ $LUA_ERRORS != "" ]]
    then
        echo
        echo " Presione <enter> para salir."
        echo -n " >>"
        read tecla
        break
    fi
    if [[ ! -e "$DALCLICK_HOME/loop" ]]
    then
        break
    fi
done

if [[ "$NO_BLOCK_CONFLICTING_SERVICES" != "Yes" ]]; then
  "$PWDIR"/block_conflicting_services 'unblock' && UNBLOCK="OK" || UNBLOCK="Error"
  [[ "$UNBLOCK" == "Error" ]] && {
    echo "Atención: Hubo problemas al intentar reactivar 'Gphoto2' y 'Media Transfer Protocol',"
    echo "al salir de Dalclick."
 }
fi
