#!/bin/bash

PROJECT_PATH="$1"
M=`basename "$0"`
[[ "$PROJECT_PATH" == "" ]] && { echo " ${M}> ERROR: PROJECT_PATH = '${PROJECT_PATH}'"; exit 1;}
[[ -d "$PROJECT_PATH" ]] || { echo " ${M}> ERROR: '${PROJECT_PATH}' no es un directorio"; exit 1; }

[[ -d "${PROJECT_PATH}/pp" ]] || {
   echo -n " ${M}> Creando carpeta 'pp'.."
   mkdir "${PROJECT_PATH}/pp" && echo "OK" || exit 1
}

[[ -d "${PROJECT_PATH}/.logs" ]] || {
   echo -n " ${M}> Creando carpeta '.logs'.."
   mkdir "${PROJECT_PATH}/.logs" && echo "OK" || exit 1
}

create_default_folder_if_needed() {
   [[ -d "${PROJECT_PATH}/pp/Default" ]] || {
      echo -n " ${M}> Creando carpeta 'pp/Default' para mover los archivos de postproceso.."
      mkdir "${PROJECT_PATH}/pp/Default" && echo "OK" || exit 1
   }
}

scantailor_replace_paths() {
   echo " ${M}> corrigiendo rutas internas en archivos scantailor en '"${PROJECT_PATH}/done/"'"
   local scantailor_files=`find "${PROJECT_PATH}/done/" -mindepth 1 -maxdepth 1 -iname "*.scantailor"`
   DEFAULT_IFS=$IFS
   IFS=$'\n'
   for f in $scantailor_files
    do
     echo -n " ${M}>  - procesando '$f'"
     sed -i 's|/done/.processing|/pp/Default/processing|g' "$f" && echo "OK" || exit 1
   done
   IFS=$DEFAULT_IFS
}

[[ -d "${PROJECT_PATH}/done/.processing" ]] && {
   echo " ${M}> Existen archivos de postproceso en el proyecto."
   scantailor_replace_paths
   create_default_folder_if_needed
   echo -n " ${M}> Moviendo carpeta '.processing'.."
   mv "${PROJECT_PATH}/done/.processing" "${PROJECT_PATH}/pp/Default/" && echo "OK" || exit 1
   echo -n " ${M}> Renombrando carpeta '.processing'  a 'processing'.."
   mv "${PROJECT_PATH}/pp/Default/.processing" "${PROJECT_PATH}/pp/Default/processing" && echo "OK" || exit 1
}


[[ -d "${PROJECT_PATH}/done/.logs" ]] && {
   create_default_folder_if_needed
   echo -n " ${M}> Moviendo carpeta '.logs'"
   mv "${PROJECT_PATH}/done/.logs" "${PROJECT_PATH}/pp/Default/.logs" && echo "OK" || exit 1
}

if find "${PROJECT_PATH}/done/" -mindepth 1 -maxdepth 1 -iname "*.scantailor" | grep -q .
 then
   create_default_folder_if_needed
   echo -n " ${M}> Moviendo achivos '*.scantailor' encontrados en 'done'.."
   mv "${PROJECT_PATH}/done/"*.scantailor "${PROJECT_PATH}/pp/Default/" && echo "OK" || exit 1
fi

[[ -f "${PROJECT_PATH}/done/output.pdf" ]] && {
   echo -n " ${M}> Renombrando 'output.pdf' a 'output_Default.pdf'.."
   mv "${PROJECT_PATH}/done/output.pdf" "${PROJECT_PATH}/done/output_Default.pdf" && echo "OK" || exit 1
}

# futuras migraciones posteriores aqui
# ./XXXXXXXXXnext_migration_script "$PROJECT_PATH" || exit 1

echo "debug: script devolviendo '0'"
exit 0
